import Head from 'next/head';
import { useContext } from 'react';
import { ThemeContext } from '@/context/themeContext';
import Calendar from '@/components/calendar';

export default function Home() {
  const { theme, toggleTheme } = useContext(ThemeContext)!;

  const handleThemeToggle = () => {
    toggleTheme();
  }

  return (
    <>
      <Head>
        <title>Loon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={theme === 'dark' ? 'dark' : 'light'}>
        <main className='bg-white dark:bg-black'>
          <Calendar />
          <button onClick={handleThemeToggle}>Toggle</button>
        </main>
      </body>
    </>
  );
}
