import Head from 'next/head';
import Header from '@/components/header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Loon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className='dark'>
        <main className='bg-white dark:bg-black '>
          <Header />
        </main>
      </body>
    </>
  );
}
